In [1]:
import pandas as pd

In [2]:
nfhs= pd.read_csv("../Datasets/Raw_Data/NFHS/NFHS-5-States.csv")

In [3]:
nfhs.isnull().sum()

state             0
state_code      131
indicator         0
nfhs5_urban     154
nfhs5_rural     212
nfhs5_total      48
nfhs4_total    1187
dtype: int64

In [4]:
nfhs.dtypes

state              str
state_code         str
indicator          str
nfhs5_urban    float64
nfhs5_rural    float64
nfhs5_total    float64
nfhs4_total    float64
dtype: object

In [5]:
nfhs["state"].unique()

<StringArray>
[                               'India',
            'Andaman & Nicobar Islands',
                       'Andhra Pradesh',
                    'Arunachal Pradesh',
                                'Assam',
                                'Bihar',
                           'Chandigarh',
                         'Chhattisgarh',
 'Dadra & Nagar Haveli and Daman & Diu',
                            'NCT Delhi',
                                  'Goa',
                              'Gujarat',
                     'Himachal Pradesh',
                              'Haryana',
                            'Jharkhand',
                      'Jammu & Kashmir',
                            'Karnataka',
                               'Kerala',
                          'Lakshadweep',
                               'Ladakh',
                          'Maharashtra',
                            'Meghalaya',
                              'Manipur',
                       'Madhya Pradesh',
                              'Mizoram',
                             'Nagaland',
                               'Odisha',
                               'Punjab',
                           'Puducherry',
                            'Rajasthan',
                               'Sikkim',
                            'Telangana',
                           'Tamil Nadu',
                              'Tripura',
                        'Uttar Pradesh',
                          'Uttarakhand',
                          'West Bengal']
Length: 37, dtype: str

In [6]:
nfhs = nfhs.drop_duplicates()

In [7]:
nfhs.duplicated().sum()

np.int64(0)

In [8]:
nfhs.columns = nfhs.columns.str.strip().str.replace(" ","_")

In [9]:
nfhs["state"]=nfhs["state"].str.strip()

In [10]:
nfhs.isnull().sum()

state             0
state_code      131
indicator         0
nfhs5_urban     154
nfhs5_rural     212
nfhs5_total      48
nfhs4_total    1187
dtype: int64

In [11]:
nfhs.to_csv("../Datasets/Processed_Data/NFHS_Clean.csv", index=False)

In [12]:
nfhs["indicator"].unique()

<StringArray>
[                                '1. Female population age 6 years and above who ever attended school (%)',
                                                                    '2. Population below age 15 years (%)',
                                          '3. Sex ratio of the total population (females per 1,000 males)',
                '4. Sex ratio at birth for children born in the last five years (females per 1,000 males)',
                   '5. Children under age 5 years whose birth was registered with the civil authority (%)',
                                   '6. Deaths in the last 3 years registered with the civil authority (%)',
                                                 '7. Population living in households with electricity (%)',
                          '8. Population living in households with an improved drinking-water source1 (%)',
                        '9. Population living in households that use an improved sanitation facility2 (%)',
                                                        '10. Households using clean fuel for cooking3 (%)',
 ...
                                           '123. Women having a mobile phone that they themselves use (%)',
   '124. Women age 15-24 years who use hygienic methods of protection during their menstrual period26 (%)',
                '125. Ever-married women age 18-49 years who have ever experienced spousal violence27 (%)',
 '126. Ever-married women age 18-49 years who have experienced physical violence during any pregnancy (%)',
                          '127. Young women age 18-29 years who experienced sexual violence by age 18 (%)',
                                       '128. Women age 15 years and above who use any kind of tobacco (%)',
                                         '129. Men age 15 years and above who use any kind of tobacco (%)',
                                               '130. Women age 15 years and above who consume alcohol (%)',
                                                 '131. Men age 15 years and above who consume alcohol (%)',
                     '66. Children age 9-35 months who received a vitamin A dose in the last 6 months (%)']
Length: 132, dtype: str

In [13]:
nfhs[nfhs["indicator"].str.contains("institution", case=False, na=False)]["indicator"].unique()

<StringArray>
['50. Institutional births (%)', '51. Institutional births in public facility (%)']
Length: 2, dtype: str

In [14]:
nfhs[nfhs["indicator"].str.contains("antenatal",case=False,na=False)]["indicator"].unique()

<StringArray>
['40. Mothers who had an antenatal check-up in the first trimester (%)', '41. Mothers who had at least 4 antenatal care visits (%)']
Length: 2, dtype: str

In [15]:
nfhs[nfhs["indicator"].str.contains("postnatal", case=False, na=False)]["indicator"].unique()

<StringArray>
['46. Mothers who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (%)', '49. Children who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (%)']
Length: 2, dtype: str

In [16]:
nfhs[nfhs["indicator"].str.contains("anaemia", case=False, na=False)]["indicator"].unique()

<StringArray>
[]
Length: 0, dtype: str

In [17]:
nfhs[nfhs["indicator"].str.contains("caesarean|cesarean|c-section", case=False, na=False)]["indicator"].unique()

<StringArray>
[                                       '54. Births delivered by caesarean section (%)',
 '55. Births in a private health facility that were delivered by caesarean section (%)',
  '56. Births in a public health facility that were delivered by caesarean section (%)']
Length: 3, dtype: str

In [18]:
nfhs[nfhs["indicator"].str.contains("delivery", case=False, na=False)]["indicator"].unique()

<StringArray>
[ '46. Mothers who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (%)',
                                              '47. Average out-of-pocket expenditure per delivery in a public health facility (Rs.)',
 '49. Children who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (%)']
Length: 3, dtype: str

In [19]:
required_indicators = [
    "40. Mothers who had an antenatal check-up in the first trimester (%)",
    "41. Mothers who had at least 4 antenatal care visits (%)",
    "46. Mothers who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (%)",
    "47. Average out-of-pocket expenditure per delivery in a public health facility (Rs.)",
    "50. Institutional births (%)",
    "54. Births delivered by caesarean section (%)"
]

nfhs_filtered = nfhs[nfhs["indicator"].isin(required_indicators)]

In [20]:
nfhs_filtered.shape

(222, 7)

In [21]:

nfhs_filtered["indicator"].unique()

<StringArray>
[                                                            '40. Mothers who had an antenatal check-up in the first trimester (%)',
                                                                         '41. Mothers who had at least 4 antenatal care visits (%)',
 '46. Mothers who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (%)',
                                             '47. Average out-of-pocket expenditure per delivery in a public health facility (Rs.)',
                                                                                                     '50. Institutional births (%)',
                                                                                    '54. Births delivered by caesarean section (%)']
Length: 6, dtype: str

In [22]:
sorted(nfhs_filtered["state"].unique())

['Andaman & Nicobar Islands',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh',
 'Dadra & Nagar Haveli and Daman & Diu',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'India',
 'Jammu & Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Ladakh',
 'Lakshadweep',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'NCT Delhi',
 'Nagaland',
 'Odisha',
 'Puducherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Telangana',
 'Tripura',
 'Uttar Pradesh',
 'Uttarakhand',
 'West Bengal']

In [23]:
nfhs_filtered.info()

<class 'pandas.DataFrame'>
Index: 222 entries, 39 to 4769
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   state        222 non-null    str
 1   state_code   216 non-null    str
 2   indicator    222 non-null    str
 3   nfhs5_urban  222 non-null    float64
 4   nfhs5_rural  216 non-null    float64
 5   nfhs5_total  222 non-null    float64
 6   nfhs4_total  222 non-null    float64
dtypes: float64(4), str(3)
memory usage: 13.9 KB

In [24]:
nfhs_filtered.isnull().sum()

state          0
state_code     6
indicator      0
nfhs5_urban    0
nfhs5_rural    6
nfhs5_total    0
nfhs4_total    0
dtype: int64

In [25]:
nfhs_filtered.duplicated().sum()

np.int64(0)

In [26]:
nfhs_filtered = nfhs_filtered.rename(columns={
    "state": "State",
    "indicator": "Indicator",
    "nfhs5_total": "NFHS5_Total",
    "nfhs5_rural": "NFHS5_Rural",
    "nfhs5_urban": "NFHS5_Urban",
    "nfhs4_total": "NFHS4_Total"
})

In [27]:
nfhs_filtered.columns

Index(['State', 'state_code', 'Indicator', 'NFHS5_Urban', 'NFHS5_Rural',
       'NFHS5_Total', 'NFHS4_Total'],
      dtype='str')

In [28]:
nfhs_pivot = nfhs_filtered.pivot(
    index="State",
    columns="Indicator",
    values="NFHS5_Total"
)

In [29]:
nfhs_pivot.head()

Indicator,40. Mothers who had an antenatal check-up in the first trimester (%),41. Mothers who had at least 4 antenatal care visits (%),46. Mothers who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (%),47. Average out-of-pocket expenditure per delivery in a public health facility (Rs.),50. Institutional births (%),54. Births delivered by caesarean section (%)
State,,,,,,
Andaman & Nicobar Islands,77.1,83.4,88.9,2924.0,99.0,29.9
Andhra Pradesh,81.7,67.5,90.7,3105.0,96.5,42.4
Arunachal Pradesh,53.1,36.5,56.4,9731.0,79.2,14.8
Assam,63.8,50.7,65.3,5415.0,84.1,18.1
Bihar,52.9,25.2,57.3,2848.0,76.2,9.7

In [30]:
nfhs_pivot = nfhs_pivot.rename(columns={
    "40. Mothers who had an antenatal check-up in the first trimester (%)": "ANC_First_Trimester",
    "41. Mothers who had at least 4 antenatal care visits (%)": "ANC_4_Visits",
    "46. Mothers who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (%)": "Postnatal_Care",
    "47. Average out-of-pocket expenditure per delivery in a public health facility (Rs.)": "Delivery_Cost_Public",
    "50. Institutional births (%)": "Institutional_Births",
    "54. Births delivered by caesarean section (%)": "Caesarean_Births"
})

In [31]:
nfhs_pivot.head()

Indicator,ANC_First_Trimester,ANC_4_Visits,Postnatal_Care,Delivery_Cost_Public,Institutional_Births,Caesarean_Births
State,,,,,,
Andaman & Nicobar Islands,77.1,83.4,88.9,2924.0,99.0,29.9
Andhra Pradesh,81.7,67.5,90.7,3105.0,96.5,42.4
Arunachal Pradesh,53.1,36.5,56.4,9731.0,79.2,14.8
Assam,63.8,50.7,65.3,5415.0,84.1,18.1
Bihar,52.9,25.2,57.3,2848.0,76.2,9.7

In [32]:
nfhs_pivot = nfhs_pivot.reset_index()

In [33]:
nfhs_pivot.head()

Indicator,State,ANC_First_Trimester,ANC_4_Visits,Postnatal_Care,Delivery_Cost_Public,Institutional_Births,Caesarean_Births
0,Andaman & Nicobar Islands,77.1,83.4,88.9,2924.0,99.0,29.9
1,Andhra Pradesh,81.7,67.5,90.7,3105.0,96.5,42.4
2,Arunachal Pradesh,53.1,36.5,56.4,9731.0,79.2,14.8
3,Assam,63.8,50.7,65.3,5415.0,84.1,18.1
4,Bihar,52.9,25.2,57.3,2848.0,76.2,9.7

In [34]:
nfhs_pivot.info()

<class 'pandas.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   State                 37 non-null     str
 1   ANC_First_Trimester   37 non-null     float64
 2   ANC_4_Visits          37 non-null     float64
 3   Postnatal_Care        37 non-null     float64
 4   Delivery_Cost_Public  37 non-null     float64
 5   Institutional_Births  37 non-null     float64
 6   Caesarean_Births      37 non-null     float64
dtypes: float64(6), str(1)
memory usage: 2.2 KB

In [35]:
nfhs_pivot.shape

(37, 7)

In [36]:
nfhs_pivot.isnull().sum()

Indicator
State                   0
ANC_First_Trimester     0
ANC_4_Visits            0
Postnatal_Care          0
Delivery_Cost_Public    0
Institutional_Births    0
Caesarean_Births        0
dtype: int64

In [37]:
nfhs_pivot.columns

Index(['State', 'ANC_First_Trimester', 'ANC_4_Visits', 'Postnatal_Care',
       'Delivery_Cost_Public', 'Institutional_Births', 'Caesarean_Births'],
      dtype='str', name='Indicator')

In [38]:
nfhs_pivot.columns.name = None

In [39]:
print(nfhs_pivot.columns)

Index(['State', 'ANC_First_Trimester', 'ANC_4_Visits', 'Postnatal_Care',
       'Delivery_Cost_Public', 'Institutional_Births', 'Caesarean_Births'],
      dtype='str')

In [40]:
nfhs_pivot.to_csv(
    "../Datasets/Processed_Data/NFHS_Clean.csv",
    index=False
)

In [41]:
nfhs_pivot.rename(columns={
    "ANC_First_Trimester": "ANC_First",
    "ANC_4_Visits": "ANC_4",
    "Postnatal_Care": "PNC_2Days",
    "Delivery_Cost_Public": "Delivery_Cost",
    "Institutional_Births": "Institutional_Delivery",
    "Caesarean_Births": "CSection_Rate"
}, inplace=True)

In [42]:
nfhs_pivot.to_csv(
    "../Datasets/Processed_Data/NFHS_Clean.csv",
    index=False
)

In [43]:
doctors = pd.read_csv("../Datasets/Raw_Data/RHS/Doctors_at_PHCs.csv")

In [44]:
doctors.info()
doctors.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   S_No             37 non-null     float64
 1   State_UT         38 non-null     str
 2   2005_Required    38 non-null     str
 3   2005_Sanctioned  34 non-null     str
 4   2005_InPosition  34 non-null     str
 5   2005_Vacant      34 non-null     str
 6   2005_Shortfall   34 non-null     str
 7   2022_Required    37 non-null     float64
 8   2022_Sanctioned  35 non-null     str
 9   2022_InPosition  37 non-null     str
 10  2022_Vacant      35 non-null     str
 11  2022_Shortfall   37 non-null     str
dtypes: float64(2), str(10)
memory usage: 3.7 KB

S_No               1
State_UT           0
2005_Required      0
2005_Sanctioned    4
2005_InPosition    4
2005_Vacant        4
2005_Shortfall     4
2022_Required      1
2022_Sanctioned    3
2022_InPosition    1
2022_Vacant        3
2022_Shortfall     1
dtype: int64

In [45]:
doctors_clean = doctors[[
    "State_UT",
    "2022_Required",
    "2022_Sanctioned",
    "2022_InPosition",
    "2022_Vacant",
    "2022_Shortfall"
]]

In [46]:
doctors_clean.info()
doctors_clean.isnull().sum()
doctors_clean.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   State_UT         38 non-null     str
 1   2022_Required    37 non-null     float64
 2   2022_Sanctioned  35 non-null     str
 3   2022_InPosition  37 non-null     str
 4   2022_Vacant      35 non-null     str
 5   2022_Shortfall   37 non-null     str
dtypes: float64(1), str(5)
memory usage: 1.9 KB

np.int64(0)

In [47]:
doctors_clean.to_csv(
    "../Datasets/Processed_Data/RHS/Doctors_Clean.csv",
    index=False
)

In [48]:
specialists = pd.read_csv("../Datasets/Raw_Data/RHS/Specialists_at_CHCs.csv")

In [49]:
specialists.info()
specialists.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   S_No             37 non-null     float64
 1   State_UT         38 non-null     str
 2   2005_Required    38 non-null     str
 3   2005_Sanctioned  33 non-null     str
 4   2005_InPosition  32 non-null     str
 5   2005_Vacant      32 non-null     str
 6   2005_Shortfall   32 non-null     str
 7   2022_Required    37 non-null     float64
 8   2022_Sanctioned  33 non-null     str
 9   2022_InPosition  37 non-null     str
 10  2022_Vacant      33 non-null     str
 11  2022_Shortfall   37 non-null     str
dtypes: float64(2), str(10)
memory usage: 3.7 KB

S_No               1
State_UT           0
2005_Required      0
2005_Sanctioned    5
2005_InPosition    6
2005_Vacant        6
2005_Shortfall     6
2022_Required      1
2022_Sanctioned    5
2022_InPosition    1
2022_Vacant        5
2022_Shortfall     1
dtype: int64

In [50]:
specialists_clean = specialists[[
    "State_UT",
    "2022_Required",
    "2022_Sanctioned",
    "2022_InPosition",
    "2022_Vacant",
    "2022_Shortfall"
]]

In [51]:
specialists_clean.info()
specialists_clean.isnull().sum()
specialists_clean.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   State_UT         38 non-null     str
 1   2022_Required    37 non-null     float64
 2   2022_Sanctioned  33 non-null     str
 3   2022_InPosition  37 non-null     str
 4   2022_Vacant      33 non-null     str
 5   2022_Shortfall   37 non-null     str
dtypes: float64(1), str(5)
memory usage: 1.9 KB

np.int64(0)

In [52]:
specialists_clean.to_csv(
    "../Datasets/Processed_Data/RHS/Specialists_Clean.csv",
    index=False
)

In [53]:
nursing = pd.read_csv("../Datasets/Raw_Data/RHS/Nursing_Staff.csv")

In [54]:
nursing.info()
nursing.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   S_No             37 non-null     float64
 1   State_UT         38 non-null     str
 2   2005_Required    38 non-null     str
 3   2005_Sanctioned  34 non-null     str
 4   2005_InPosition  34 non-null     str
 5   2005_Vacant      34 non-null     str
 6   2005_Shortfall   34 non-null     str
 7   2022_Required    37 non-null     float64
 8   2022_Sanctioned  35 non-null     str
 9   2022_InPosition  37 non-null     str
 10  2022_Vacant      35 non-null     str
 11  2022_Shortfall   37 non-null     str
dtypes: float64(2), str(10)
memory usage: 3.7 KB

S_No               1
State_UT           0
2005_Required      0
2005_Sanctioned    4
2005_InPosition    4
2005_Vacant        4
2005_Shortfall     4
2022_Required      1
2022_Sanctioned    3
2022_InPosition    1
2022_Vacant        3
2022_Shortfall     1
dtype: int64

In [55]:
nursing_clean = nursing[[
    "State_UT",
    "2022_Required",
    "2022_Sanctioned",
    "2022_InPosition",
    "2022_Vacant",
    "2022_Shortfall"
]]

In [56]:
nursing_clean.info()
nursing_clean.isnull().sum()
nursing_clean.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   State_UT         38 non-null     str
 1   2022_Required    37 non-null     float64
 2   2022_Sanctioned  35 non-null     str
 3   2022_InPosition  37 non-null     str
 4   2022_Vacant      35 non-null     str
 5   2022_Shortfall   37 non-null     str
dtypes: float64(1), str(5)
memory usage: 1.9 KB

np.int64(0)

In [57]:
nursing_clean.to_csv(
    "../Datasets/Processed_Data/RHS/Nursing_Clean.csv",
    index=False
)

In [58]:
facilities = pd.read_csv("../Datasets/Raw_Data/RHS/Facilities_Count.csv")

In [59]:
facilities.columns

Index(['S_No', 'State_UT', 'SubCentres_Rural', 'SubCentres_Urban',
       'PHCs_Rural', 'PHCs_Urban', 'CHCs_Rural', 'CHCs_Urban'],
      dtype='str')

In [60]:
facilities_clean = facilities[[
    "State_UT",
    "SubCentres_Rural",
    "SubCentres_Urban",
    "PHCs_Rural",
    "PHCs_Urban",
    "CHCs_Rural",
    "CHCs_Urban"
]]

In [61]:
facilities_clean.info()
facilities_clean.isnull().sum()
facilities_clean.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   State_UT          37 non-null     str
 1   SubCentres_Rural  37 non-null     int64
 2   SubCentres_Urban  37 non-null     int64
 3   PHCs_Rural        37 non-null     int64
 4   PHCs_Urban        37 non-null     int64
 5   CHCs_Rural        37 non-null     int64
 6   CHCs_Urban        37 non-null     int64
dtypes: int64(6), str(1)
memory usage: 2.2 KB

np.int64(0)

In [62]:
facilities_clean.to_csv(
    "../Datasets/Processed_Data/RHS/Facilities_Clean.csv",
    index=False
)

In [63]:
shortfall= pd.read_csv("../Datasets/Raw_Data/RHS/Facility_Shortfall.csv")

In [64]:
shortfall.columns

Index(['S_No', 'State_UT', 'Est_MidYear_Pop_Rural', 'Est_MidYear_Pop_Tribal',
       'SC_Required', 'SC_InPosition', 'SC_Shortfall', 'SC_PctShortfall',
       'PHC_Required', 'PHC_InPosition', 'PHC_Shortfall', 'PHC_PctShortfall',
       'CHC_Required', 'CHC_InPosition', 'CHC_Shortfall', 'CHC_PctShortfall'],
      dtype='str')

In [65]:
shortfall.info()
shortfall.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   S_No                    36 non-null     float64
 1   State_UT                37 non-null     str
 2   Est_MidYear_Pop_Rural   37 non-null     int64
 3   Est_MidYear_Pop_Tribal  37 non-null     int64
 4   SC_Required             37 non-null     str
 5   SC_InPosition           37 non-null     str
 6   SC_Shortfall            37 non-null     str
 7   SC_PctShortfall         37 non-null     str
 8   PHC_Required            37 non-null     str
 9   PHC_InPosition          37 non-null     str
 10  PHC_Shortfall           37 non-null     str
 11  PHC_PctShortfall        37 non-null     str
 12  CHC_Required            37 non-null     str
 13  CHC_InPosition          37 non-null     str
 14  CHC_Shortfall           37 non-null     str
 15  CHC_PctShortfall        37 non-null     str
dtypes: float64(1), int64(2), str(13)
memory usage: 4.8 KB

S_No                      1
State_UT                  0
Est_MidYear_Pop_Rural     0
Est_MidYear_Pop_Tribal    0
SC_Required               0
SC_InPosition             0
SC_Shortfall              0
SC_PctShortfall           0
PHC_Required              0
PHC_InPosition            0
PHC_Shortfall             0
PHC_PctShortfall          0
CHC_Required              0
CHC_InPosition            0
CHC_Shortfall             0
CHC_PctShortfall          0
dtype: int64

In [66]:
shortfall_clean = shortfall[[
    "State_UT",
    "SC_Required",
    "SC_InPosition",
    "SC_Shortfall",
    "SC_PctShortfall",
    "PHC_Required",
    "PHC_InPosition",
    "PHC_Shortfall",
    "PHC_PctShortfall",
    "CHC_Required",
    "CHC_InPosition",
    "CHC_Shortfall",
    "CHC_PctShortfall"
]]

In [67]:
shortfall_clean.info()
shortfall_clean.isnull().sum()
shortfall_clean.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   State_UT          37 non-null     str
 1   SC_Required       37 non-null     str
 2   SC_InPosition     37 non-null     str
 3   SC_Shortfall      37 non-null     str
 4   SC_PctShortfall   37 non-null     str
 5   PHC_Required      37 non-null     str
 6   PHC_InPosition    37 non-null     str
 7   PHC_Shortfall     37 non-null     str
 8   PHC_PctShortfall  37 non-null     str
 9   CHC_Required      37 non-null     str
 10  CHC_InPosition    37 non-null     str
 11  CHC_Shortfall     37 non-null     str
 12  CHC_PctShortfall  37 non-null     str
dtypes: str(13)
memory usage: 3.9 KB

np.int64(0)

In [68]:
shortfall_clean.to_csv(
    "../Datasets/Processed_Data/RHS/Shortfall_Clean.csv",
    index=False
)

In [69]:
mmr = pd.read_csv("../Datasets/Raw_Data/SRS/SRS_Table1_MMR_2022-24.csv")

trend = pd.read_csv("../Datasets/Raw_Data/SRS/SRS_MMR_trend_2014-2024.csv")

age = pd.read_csv("../Datasets/Raw_Data/SRS/SRS_Table2_AgeDistribution_2022-24.csv")

In [70]:
mmr.info()
mmr.isnull().sum()
mmr.duplicated().sum()

trend.info()
trend.isnull().sum()
trend.duplicated().sum()

age.info()
age.isnull().sum()
age.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   State_Group              24 non-null     str
 1   MMR                      24 non-null     int64
 2   CI_Lower                 24 non-null     int64
 3   CI_Upper                 24 non-null     int64
 4   Maternal_Mortality_Rate  24 non-null     int64
 5   Lifetime_Risk_Pct        24 non-null     float64
dtypes: float64(1), int64(4), str(1)
memory usage: 1.3 KB
<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Period  9 non-null      str
 1   MMR     9 non-null      int64
dtypes: int64(1), str(1)
memory usage: 276.0 bytes
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age_Group               8 non-null      str
 1   Maternal_Deaths_Pct     8 non-null      int64
 2   Maternal_CI_Lower       7 non-null      float64
 3   Maternal_CI_Upper       7 non-null      float64
 4   NonMaternal_Deaths_Pct  8 non-null      int64
 5   NonMaternal_CI_Lower    7 non-null      float64
 6   NonMaternal_CI_Upper    7 non-null      float64
dtypes: float64(4), int64(2), str(1)
memory usage: 580.0 bytes

np.int64(0)

In [71]:
mmr.isnull().sum()

State_Group                0
MMR                        0
CI_Lower                   0
CI_Upper                   0
Maternal_Mortality_Rate    0
Lifetime_Risk_Pct          0
dtype: int64

In [72]:
mmr.duplicated().sum()

np.int64(0)

In [73]:
trend.isnull().sum()

Period    0
MMR       0
dtype: int64

In [74]:
trend.duplicated().sum()

np.int64(0)

In [75]:

age.isnull().sum()

Age_Group                 0
Maternal_Deaths_Pct       0
Maternal_CI_Lower         1
Maternal_CI_Upper         1
NonMaternal_Deaths_Pct    0
NonMaternal_CI_Lower      1
NonMaternal_CI_Upper      1
dtype: int64

In [76]:
age.duplicated().sum()

np.int64(0)

In [77]:
mmr.to_csv("../Datasets/Processed_Data/SRS/MMR_Clean.csv", index=False)

trend.to_csv("../Datasets/Processed_Data/SRS/MMR_Trend_Clean.csv", index=False)

age.to_csv("../Datasets/Processed_Data/SRS/Age_Distribution_Clean.csv", index=False)