In [1]:
import pandas as pd
import numpy as np

In [2]:
nfhs = pd.read_csv("../Datasets/Raw_Data/NFHS/NFHS-5-States.csv")

In [3]:
birth_death = pd.read_csv("../Datasets/Raw_Data/RHS/Birth_Death_Rate.csv")
doctors = pd.read_csv("../Datasets/Raw_Data/RHS/Doctors_at_PHCs.csv")
facilities= pd.read_csv("../Datasets/Raw_Data/RHS/Facilities_Count.csv")
shortfall= pd.read_csv("../Datasets/Raw_Data/RHS/Facility_Shortfall.csv")
imr = pd.read_csv("../Datasets/Raw_Data/RHS/Infant_Mortality_Rate.csv")
nurses = pd.read_csv("../Datasets/Raw_Data/RHS/Nursing_Staff.csv")
specialists = pd.read_csv("../Datasets/Raw_Data/RHS/Specialists_at_CHCs.csv")

In [4]:
mmr = pd.read_csv("../Datasets/Raw_Data/SRS/SRS_MMR_trend_2014-2024.csv")
trend = pd.read_csv("../Datasets/Raw_Data/SRS/SRS_Table1_MMR_2022-24.csv")
age = pd.read_csv("../Datasets/Raw_Data/SRS/SRS_Table2_AgeDistribution_2022-24.csv")

In [5]:
nfhs.head()

,state,state_code,indicator,nfhs5_urban,nfhs5_rural,nfhs5_total,nfhs4_total
0,India,NaN,1. Female population age 6 years and above who...,82.5,66.8,71.8,68.8
1,India,NaN,2. Population below age 15 years (%),23.1,28.1,26.5,28.6
2,India,NaN,3. Sex ratio of the total population (females ...,985.0,1037.0,1020.0,991.0
3,India,NaN,4. Sex ratio at birth for children born in the...,924.0,931.0,929.0,919.0
4,India,NaN,5. Children under age 5 years whose birth was ...,93.3,87.5,89.1,79.7

In [6]:
doctors.head()

,S_No,State_UT,2005_Required,2005_Sanctioned,2005_InPosition,2005_Vacant,2005_Shortfall,2022_Required,2022_Sanctioned,2022_InPosition,2022_Vacant,2022_Shortfall
0,1.0,Andhra Pradesh,1570,2497,2137,360,*,1142.0,2206,2048,158,*
1,2.0,Arunachal Pradesh,85,78,78,0,7,126.0,NaN,129,NaN,*
2,3.0,Assam,610,NaN,NaN,NaN,NaN,920.0,1617,1381,236,*
3,4.0,Bihar,1648,NaN,NaN,NaN,NaN,1492.0,3595,1538,2057,*
4,5.0,Chhattisgarh,517,1034,628,406,*,770.0,967,491,476,279

In [7]:
mmr.head()

    Period  MMR
0  2014-16  130
1  2015-17  122
2  2016-18  113
3  2017-19  103
4  2018-20   97

In [8]:
nfhs.info()

<class 'pandas.DataFrame'>
RangeIndex: 4847 entries, 0 to 4846
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   state        4847 non-null   str
 1   state_code   4716 non-null   str
 2   indicator    4847 non-null   str
 3   nfhs5_urban  4693 non-null   float64
 4   nfhs5_rural  4635 non-null   float64
 5   nfhs5_total  4799 non-null   float64
 6   nfhs4_total  3660 non-null   float64
dtypes: float64(4), str(3)
memory usage: 265.2 KB

In [9]:
nfhs.shape

nfhs.columns

Index(['state', 'state_code', 'indicator', 'nfhs5_urban', 'nfhs5_rural',
       'nfhs5_total', 'nfhs4_total'],
      dtype='str')

In [ ]:
doctors.head()
doctors.info()
doctors.shape
doctors.columns

<class 'pandas.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   S_No             37 non-null     float64
 1   State_UT         38 non-null     str
 2   2005_Required    38 non-null     str
 3   2005_Sanctioned  34 non-null     str
 4   2005_InPosition  34 non-null     str
 5   2005_Vacant      34 non-null     str
 6   2005_Shortfall   34 non-null     str
 7   2022_Required    37 non-null     float64
 8   2022_Sanctioned  35 non-null     str
 9   2022_InPosition  37 non-null     str
 10  2022_Vacant      35 non-null     str
 11  2022_Shortfall   37 non-null     str
dtypes: float64(2), str(10)
memory usage: 3.7 KB

Index(['S_No', 'State_UT', '2005_Required', '2005_Sanctioned',
       '2005_InPosition', '2005_Vacant', '2005_Shortfall', '2022_Required',
       '2022_Sanctioned', '2022_InPosition', '2022_Vacant', '2022_Shortfall'],
      dtype='str')

In [19]:

facilities.head()
facilities.info()
facilities.shape
facilities.columns

<class 'pandas.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   S_No              36 non-null     float64
 1   State_UT          37 non-null     str
 2   SubCentres_Rural  37 non-null     int64
 3   SubCentres_Urban  37 non-null     int64
 4   PHCs_Rural        37 non-null     int64
 5   PHCs_Urban        37 non-null     int64
 6   CHCs_Rural        37 non-null     int64
 7   CHCs_Urban        37 non-null     int64
dtypes: float64(1), int64(6), str(1)
memory usage: 2.4 KB

Index(['S_No', 'State_UT', 'SubCentres_Rural', 'SubCentres_Urban',
       'PHCs_Rural', 'PHCs_Urban', 'CHCs_Rural', 'CHCs_Urban'],
      dtype='str')

In [12]:
shortfall.head()
shortfall.info()
shortfall.shape
shortfall.columns

<class 'pandas.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   S_No                    36 non-null     float64
 1   State_UT                37 non-null     str
 2   Est_MidYear_Pop_Rural   37 non-null     int64
 3   Est_MidYear_Pop_Tribal  37 non-null     int64
 4   SC_Required             37 non-null     str
 5   SC_InPosition           37 non-null     str
 6   SC_Shortfall            37 non-null     str
 7   SC_PctShortfall         37 non-null     str
 8   PHC_Required            37 non-null     str
 9   PHC_InPosition          37 non-null     str
 10  PHC_Shortfall           37 non-null     str
 11  PHC_PctShortfall        37 non-null     str
 12  CHC_Required            37 non-null     str
 13  CHC_InPosition          37 non-null     str
 14  CHC_Shortfall           37 non-null     str
 15  CHC_PctShortfall        37 non-null     str
dtypes: float64(1), int64(2), str(13)
memory usage: 4.8 KB

Index(['S_No', 'State_UT', 'Est_MidYear_Pop_Rural', 'Est_MidYear_Pop_Tribal',
       'SC_Required', 'SC_InPosition', 'SC_Shortfall', 'SC_PctShortfall',
       'PHC_Required', 'PHC_InPosition', 'PHC_Shortfall', 'PHC_PctShortfall',
       'CHC_Required', 'CHC_InPosition', 'CHC_Shortfall', 'CHC_PctShortfall'],
      dtype='str')

In [13]:
imr .head()
imr.info()
imr.shape
imr.columns

<class 'pandas.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   S_No       36 non-null     float64
 1   State_UT   37 non-null     str
 2   IMR_Total  37 non-null     int64
 3   IMR_Rural  37 non-null     int64
 4   IMR_Urban  36 non-null     float64
dtypes: float64(2), int64(2), str(1)
memory usage: 1.6 KB

Index(['S_No', 'State_UT', 'IMR_Total', 'IMR_Rural', 'IMR_Urban'], dtype='str')

In [14]:
nurses .head()
nurses.info()
nurses.shape
nurses.columns

<class 'pandas.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   S_No             37 non-null     float64
 1   State_UT         38 non-null     str
 2   2005_Required    38 non-null     str
 3   2005_Sanctioned  34 non-null     str
 4   2005_InPosition  34 non-null     str
 5   2005_Vacant      34 non-null     str
 6   2005_Shortfall   34 non-null     str
 7   2022_Required    37 non-null     float64
 8   2022_Sanctioned  35 non-null     str
 9   2022_InPosition  37 non-null     str
 10  2022_Vacant      35 non-null     str
 11  2022_Shortfall   37 non-null     str
dtypes: float64(2), str(10)
memory usage: 3.7 KB

Index(['S_No', 'State_UT', '2005_Required', '2005_Sanctioned',
       '2005_InPosition', '2005_Vacant', '2005_Shortfall', '2022_Required',
       '2022_Sanctioned', '2022_InPosition', '2022_Vacant', '2022_Shortfall'],
      dtype='str')

In [15]:
specialists.head()
specialists.info()
specialists.shape
specialists.columns

<class 'pandas.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   S_No             37 non-null     float64
 1   State_UT         38 non-null     str
 2   2005_Required    38 non-null     str
 3   2005_Sanctioned  33 non-null     str
 4   2005_InPosition  32 non-null     str
 5   2005_Vacant      32 non-null     str
 6   2005_Shortfall   32 non-null     str
 7   2022_Required    37 non-null     float64
 8   2022_Sanctioned  33 non-null     str
 9   2022_InPosition  37 non-null     str
 10  2022_Vacant      33 non-null     str
 11  2022_Shortfall   37 non-null     str
dtypes: float64(2), str(10)
memory usage: 3.7 KB

Index(['S_No', 'State_UT', '2005_Required', '2005_Sanctioned',
       '2005_InPosition', '2005_Vacant', '2005_Shortfall', '2022_Required',
       '2022_Sanctioned', '2022_InPosition', '2022_Vacant', '2022_Shortfall'],
      dtype='str')

In [16]:
mmr.head()
mmr.info()
mmr.shape
mmr.columns

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Period  9 non-null      str
 1   MMR     9 non-null      int64
dtypes: int64(1), str(1)
memory usage: 276.0 bytes

Index(['Period', 'MMR'], dtype='str')

In [17]:
trend.head()
trend.info()
trend.shape
trend.columns

<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   State_Group              24 non-null     str
 1   MMR                      24 non-null     int64
 2   CI_Lower                 24 non-null     int64
 3   CI_Upper                 24 non-null     int64
 4   Maternal_Mortality_Rate  24 non-null     int64
 5   Lifetime_Risk_Pct        24 non-null     float64
dtypes: float64(1), int64(4), str(1)
memory usage: 1.3 KB

Index(['State_Group', 'MMR', 'CI_Lower', 'CI_Upper', 'Maternal_Mortality_Rate',
       'Lifetime_Risk_Pct'],
      dtype='str')

In [18]:
age.head()
age.info()
age.shape
age.columns

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age_Group               8 non-null      str
 1   Maternal_Deaths_Pct     8 non-null      int64
 2   Maternal_CI_Lower       7 non-null      float64
 3   Maternal_CI_Upper       7 non-null      float64
 4   NonMaternal_Deaths_Pct  8 non-null      int64
 5   NonMaternal_CI_Lower    7 non-null      float64
 6   NonMaternal_CI_Upper    7 non-null      float64
dtypes: float64(4), int64(2), str(1)
memory usage: 580.0 bytes

Index(['Age_Group', 'Maternal_Deaths_Pct', 'Maternal_CI_Lower',
       'Maternal_CI_Upper', 'NonMaternal_Deaths_Pct', 'NonMaternal_CI_Lower',
       'NonMaternal_CI_Upper'],
      dtype='str')